# Clean-up gnomad frequency info to obtain AFR and EUR specific AFs for meSNPs

## Load libraries

In [1]:
library(readr)
library(data.table)
library(stringr)

## Obtain population-specific AF from gnomad variant annotation table AF entry

Load AF info for meSNPs obtained when filtering the gnomad HailTable

In [ ]:
dat1 <- read.csv("freq_gnomad_meSNPs.tsv",sep="")
head(dat1)
dim(dat1)

  locus        alleles
1 chr1:3827139 ["T","G"]
2 chr1:3847003 ["T","C"]
3 chr1:4728294 ["C","T"]
4 chr1:5511977 ["A","G"]
5 chr1:5525799 ["C","T"]
6 chr1:5540999 ["A","G"]
  X__uid_5
1 [0.01363540735286383,0.013647349340618925,2.6470588235294115E-4,0.0,0.003401360544217687,0.007561436672967864,0.0,5.763688760806917E-4,0.047547933326910104,0.0,4.185851820845542E-4,0.003995284254650249,0.014525384041376117,0.01270536986743392,2.541942043721403E-4,0.0,0.0,0.007619047619047619,0.0,5.353319057815846E-4,0.048726517341040464,0.0,0.0,0.004574970484061393,2.791346824842987E-4,0.0,0.006666666666666667,0.0075046904315197,0.0,6.242197253433209E-4,0.04620070204418749,0.0,5.47645125958379E-4,0.003532736693358455,0.014321819713563605,0.01406702523789822,0.0,0.0,0.03333333333333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.037037037037037035,0.0,0.015625,0.05,0.0,0.0,0.0392156862745098,0.005555555555555556,0.08771929824561403,0.0375,0.0,0.0,0.061224489795918366,0.0,0.0,0.0,0.01400679117147708,0.014632107023411372,0.0,0.0,0.039473684210526314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.03636363636363636,0.0,0.021739130434782608,0.06666666666666667,0.0,0.0,0.03571428571428571,0.01020408163265306,0.10714285714285714,0.022727272727272728,0.0,0.0,0.011111111111111112,0.0,0.0,0.0,0.0,0.0,0.02702702702702703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.03773584905660377,0.0,0.01,0.03333333333333333,0.0,0.0,0.043478260869565216,0.0,0.06896551724137931,0.05555555555555555,0.0,0.0,0.10377358490566038,0.0,0.0,0.0,0.005263157894736842,0.005263157894736842,0.0,0.0,0.013157894736842105,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.047619047619047616,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003401360544217687,0.006238859180035651,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.07142857142857142,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.05,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.038461538461538464,0.05555555555555555,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.038461538461538464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.045454545454545456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06818181818181818,0.0,0.0,0.0,0.0,0.0,null,0.06818181818181818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,null,null,0.0]
2 [0.02187729803550793,0.021909161297095837,3.822068032810984E-4,0.0,0.003401360544217687,0.015137180700094607,0.0,5.763688760806917E-4,0.07589393137302083,0.0,4.139072847682119E-4,0.007517322525820369,0.022770496016448215,0.020944095376188174,3.303684879288437E-4,0.0,0.0,0.015238095238095238,0.0,5.359056806002144E-4,0.07587109586567972,0.0,0.0,0.00898379970544919,4.5334077277165574E-4,0.0,0.006666666666666667,0.015037593984962405,0.0,6.234413965087282E-4,0.07592000824657252,0.0,5.43773790103317E-4,0.006346967559943582,0.020933977455716585,0.020933977455716585,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06521739130434782,0.0058823529411764705,0.025252525252525252,0.08152173913043478,0.0,0.0,0.049019607843137254,0.005319148936170213,0.11206896551724138,0.05232558139534884,0.0,0.0,0.09223300970873786,0.0,0.0,0.0,0.0210016155088853,0.02086677367576244,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06896551724137931,0.011627906976744186,0.031914893617021274,0.07446808510638298,0.0,0.0,0.05357142857142857,0.00980392156862745,0.14035087719298245,0.043478260869565216,0.0,0.0,0.0425531914893617,0.0,0.0,0.0,0.0,0.0,0.0375,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06140350877192982,0.0,0.019230769230769232,0.08888888888888889,0.0,0.0,0.043478260869565216,0.0,0.0847457627118644,0.0625,0.0,0.0,0.13392857142857142,0.0,0.0,0.0,0.011695906432748537,0.011695906432748537,0.0,0.0,0.02631578947368421,0.05,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.07142857142857142,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008503401360544218,0.013368983957219251,0.0,0.0,0.02,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.14285714285714285,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.1,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.038461538461538464,0.05555555555555555,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.23076923076923078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.045454545454545456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.09090909090909091,0.0,0.0,0.0,0.0,0.08333333333333333,null,0.09090909090909091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,null,null,0.08333333333333333]
3 [0.015373795533120375,0.01545803029905217,0.007426907465145008,0.05705394190871369,0.006802721088435374,0.01890359168241966,0.0,0.021889400921658985,0.0014697378565921358,0.15655387008945934,0.03451143451143451,0.005166099921527596,0.012165950770338742,0.01872714562271456,0.007143220295897097,0.05439005439005439,0.0,0.018095238095238095,0.0,0.017130620985010708,0.0016268980477223427,0.16237799467613132,0.028745644599303136,0.005748820754716981,0.007816316560820713,0.05790784557907846,0.013333333333333334,0.019699812382739212,0.0,0.02743142144638404,0.0012902559867877788,0.15200831024930747,0.0363189513926816,0.004701457451810061,0.03884863123993559,0.03884863123993559,0.1590909090909091,0.015,0.0,0.0,0.045454545454545456,0.0392156862745098,0.004201680672268907,0.0048543689320388345,0.05102040816326531,0.020833333333333332,0.0,0.011764705882352941,0.005050505050505051,0.0,0.14705882352941177,0.008064516129032258,0.0,0.010638297872340425,0.0,0.0,0.005747126436781609,0.12254901960784313,0.0,0.18137254901960784,0.10891089108910891,0.04081632653061224,0.03796445880452343,0.039727126805778494,0.14130434782608695,0.0,0.0,0.0,0.0392156862745098,0.047619047619047616,0.00847457627118644,0.01,0.05,0.010869565217391304,0.0,0.0,0.0,0.0,0.12745098039215685,0.016666666666666666,0.0,0.00980392156862745,0.0,0.0,0.011904761904761904,0.10526315789473684,0.0,0.22826086956521738,0.12037037037037036,0.023809523809523808,0.17857142857142858,0.027777777777777776,0.0,0.0,0.052083333333333336,0.03333333333333333,0.0,0.0,0.05263157894736842,0.03,0.0,0.023809523809523808,0.009615384615384616,0.0,0.16666666666666666,0.0,0.0,0.011627906976744186,0.0,0.0,0.0,0.14444444444444443,0.0,0.14285714285714285,0.09574468085106383,0.05357142857142857,0.04689331770222743,0.04689331770222743,0.0,0.020833333333333332,0.0,0.0,0.0,0.0,0.0,0.2,0.2222222222222222,0.045454545454545456,0.0,0.2,0.0,0.0,0.0,0.03571428571428571,0.023809523809523808,0.16666666666666666,0.06521739130434782,0.07142857142857142,0.0,0.0,0.1,0.2222222222222222,0.02,0.022727272727272728,0.0,0.018518518518518517,0.0,0.0,0.0,0.2,0.020833333333333332,0.03125,0.15,0.0,0.04,0.0,0.0625,0.25,0.0,0.25,0.06818181818181818,0.0,0.07142857142857142,0.1875,0.04607508532423208,0.04732142857142857,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.16666666666666666,0.0,0.0,0.0,0.0,0.0,0.0,0.0625,0.029411764705882353,0.3333333333333333,null,0.0,0.0,0.0,0.16666666666666666,0.0,0.05555555555555555,null,0.0,0.0,0.0,0.0,0.0,0.5,0.1,null,0.125,0.0,0.07142857142857142,0.0,0.0,0.16666666666666666,0.0,0.25,0.25,0.0,0.0625,0.3333333333333333,0.0,0.025,0.0,0.0,0.0,0.0,0.0,0.2857142857142857,0.25,0.05555555555555555,0.0,0.2222222222222222,0.0,0.0,0.0,0.0,0.02,0.08333333333333333,0.06521739130434782,0.1,0.0,0.0,0.07142857142857142,0.25,0.0,0.022727272727272728,0.0,0.03333333333333333,0.0,0.0,0.0,0.16666666666666666,0.0,0.03125,0.16666666666666666,0.0,0.027777777777777776,0.0,0.08333333333333333,0.2857142857142857,0.0,0.25,0.027777777777777776,0.0,0.075,0.1,0.18181818181818182,0.05,0.19444444444444445,0.16666666666666666,0.0,0.0625,0.0,0.0,0.0,0.5,0.5,0.0,null,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.5,null,null,0.0]
4 [0.022815036645913785,0.022853430967284753,3.3817561606775277E-4,0.0,0.006802721088435374,0.012287334593572778,0.0,0.0,0.07892836510687463,0.0,4.1476565740356696E-4,0.009278619968635651,0.023233699144156877,0.022377434519811955,3.812913065582105E-4,0.0,0.013888888888888888,0.01619047619047619,0.0,0.0,0.0771278996299305,0.0,8.695652173913044E-4,0.009417304296645085,2.7901785714285713E-4,0.0,0.0,0.008442776735459663,0.0,0.0,0.0809862787578665,0.0,2.723311546840959E-4,0.009167842031029619,0.02717391304347826,0.02717391304347826,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1782608695652174,0.0,0.015151515151515152,0.10869565217391304,0.0,0.03225806451612903,0.058823529411764705,0.0,0.09051724137931035,0.09883720930232558,0.0,0.0,0.06310679611650485,0.0,0.0,0.0,0.027463651050080775,0.026886035313001606,0.0,0.0,0.075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.13793103448275862,0.0,0.02127659574468085,0.1276595744680851,0.0,0.016666666666666666,0.05357142857142857,0.0,0.10526315789473684,0.11956521739130435,0.0,0.0,0.05319148936170213,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.21929824561403508,0.0,0.009615384615384616,0.08888888888888889,0.0,0.046875,0.06521739130434782,0.0,0.07627118644067797,0.075,0.0,0.0,0.07142857142857142,0.0,0.0,0.0,0.009941520467836258,0.009941520467836258,0.0,0.0,0.02631578947368421,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.125,0.0,0.0,0.011904761904761904,0.0,0.021739130434782608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.023809523809523808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.011904761904761904,0.008912655971479501,0.0,0.0,0.04,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.21428571428571427,0.0,0.0,0.029411764705882353,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.05,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16666666666666666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.07692307692307693,0.0,0.0,0.0,0.0,0.021739130434782608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06818181818181818,0.0,0.0,0.0,0.0,0.08333333333333333,null,0.06818181818181818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,null,null,0.08333333333333333]
5 [0.02608838400420251,0.026185258572047187,7.350130832328815E-5,0.0,0.003401360544217687,0.0222117202268431,0.0,0.0,0.09162694400308151,0.0,0.0,0.007450980392156863,0.02728230698056955,0.024840884066922683,5.0831088293600365E-5,0.0,0.006944444444444444,0.023809523809523808,0.0,0.0,0.09223476297968397,0.0,0.0,0.0076560659599528855,1.0460251046025104E-4,0.0,0.0,0.020637898686679174,0.0,0.0,0.09093253558902414,0.0,0.0,0.007287259050305595,0.0265914585012087,0.026972624798711754,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06521739130434782,0.0058823529411764705,0.010101010101010102,0.125,0.0,0.008064516129032258,0.10784313725490197,0.010638297872340425,0.12931034482758622,0.023529411764705882,0.0,0.0,0.13106796116504854,0.0,0.0,0.0,0.025464834276475345,0.027710843373493974,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06896551724137931,0.011627906976744186,0.02127659574468085,0.13829787234042554,0.0,0.0,0.10714285714285714,0.00980392156862745,0.12280701754385964,0.011111111111111112,0.0,0.0,0.1276595744680851,0.0,0.0,0.0,0.0,0.0,0.1375,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06140350877192982,0.0,0.0,0.1111111111111111,0.0,0.015625,0.10869565217391304,0.011627906976744186,0.13559322033898305,0.0375,0.0,0.0,0.13392857142857142,0.0,0.0,0.0,0.014035087719298246,0.014035087719298246,0.0,0.0,0.013157894736842105,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16666666666666666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006802721088435374,0.017825311942959002,0.0,0.0,0.02,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.14285714285714285,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.05,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.038461538461538464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2727272727272727,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.22727272727272727,0.0,0.0,0.0,0.0,0.16666666666666666,null,0.22727272727272727,0.0,0.0,0.0,0.0,0.0,0.0,0.0,null,null,0.16666666666666666]
6 [0.025309218049658907,0.02533797086231789,7.360518180479906E-5,0.0,0.003401360544217687,0.021347248576850095,0.0,0.0,0.0887706457360235,0.0,0.0,0.007392385189061886,0.026723251028806586,0.023831285787252344,5.08854060655404E-5,0.0,0.006944444444444444,0.02385496183206107,0.0,0.0,0.09019501625135427,0.0,0.0,0.0076650943396226415,1.0479983232026829E-4,0.0,0.0,0.018867924528301886,0.0,0.0,0.08714270973067795,0.0,0.0,0.007174782404140202,0.026167471819645734,0.026167471819645734,0.0,0.0,0.0875,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06956521739130435,0.0058823529411764705,0.010101010101010102,0.11413043478260869,0.0,0.008064516129032258,0.10784313725490197,0.010638297872340425,0.12931034482758622,0.029069767441860465,0.0,0.0,0.13106796116504854,0.0,0.0,0.0,0.02544426494345719,0.026886035313001606,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.07758620689655173,0.011627906976744186,0.02127659574468085,0.1276595744680851,0.0,0.0,0.10714285714285714,0.00980392156862745,0.12280701754385964,0.021739130434782608,0.0,0.0,0.1276595744680851,0.0,0.0,0.0,0.0,0.0,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06140350877192982,0.0,0.0,0.1,0.0,0.015625,0.10869565217391304,0.011627906976744186,0.13559322033898305,0.0375,0.0,0.0,0.13392857142857142,0.0,0.0,0.0,0.00760233918128655,0.00760233918128655,0.0,0.0,0.013157894736842105,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16666666666666666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006802721088435374,0.008021390374331552,0.0,0.0,0.02,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.14285714285714285,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,null,0.0,0.0,0.05,0.0,0.0,0.0,0.0,null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.038461538461538464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2727272727272727,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.022727272727272728,0.0,0.0,0.0,0.0,0.0,null,0.022727272727272728,0.0,0.0,0.0,0.0,0.0,0.0,0.0,null,null,0.0]

[1] 2636    3

[1] 2238

Load gnomad frequency globals (information on AF HailTable contents) and process data accordingly

In [ ]:
globals <- read.csv("freq_globals.tsv",sep="")
head(globals)

  freq_meta

The information stored in the AF metadata is informing as for the order that the population specific AFs appear in the frequency column. More specifically, the first 12 sequencies from gnomad AF entry represent the raw and adjusted allele frequency in a global scale, as well as adjusted AFs for 9 different population groups and an additional group called  "remaining individuals" group.

In [ ]:
proc <- dat1
proc$X__uid_5 <- stringr::str_extract(proc$X__uid_5, "^([^,]+,){12}") # Extract first 12 entries with AFs of interest

[1] 12

Remove "[" and last comma

In [ ]:
proc$X__uid_5 <- gsub("\\[","",proc$X__uid_5)
proc$X__uid_5 <-  gsub(",$", "", proc$X__uid_5)

  locus          alleles
1 chr1:100606439 ["A","G"]
2 chr1:100606439 ["AGAC","A"]
3 chr1:100803863 ["A","G"]
4 chr1:101639888 ["T","C"]
5 chr1:106757252 ["T","C"]
6 chr1:107298833 ["A","G"]
  X__uid_5
1 0.9729000315192268,0.9728589610696338,0.999647266313933,0.9998117115420825,0.9897959183673469,0.9820245979186376,1.0,1.0,0.90621387283237,1.0,0.9991714995857498,0.9894103804418878
2 0.0,6.565643301730704E-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3 0.01874318877115584,0.018799212598425197,4.1157102539981187E-4,0.0,0.003401360544217687,0.015610217596972564,0.0,0.0,0.06301732435033686,0.0023121387283236996,0.01805728518057285,0.004902601647274154
4 0.02305046022137896,0.023088733170616486,4.850943729052743E-4,1.8814675446848542E-4,0.003401360544217687,0.017013232514177693,0.0,0.0034602076124567475,0.07937157155230488,0.0,0.0,0.00837257980115123
5 0.015953251124023873,0.015973853807079948,8.82716412640499E-5,0.0,0.0,0.0071090047393364926,0.0,0.0,0.05591946825931991,0.0,2.0703933747412008E-4,0.005437631027253669
6 0.987247678709796,0.987240044610641,0.9999411989533413,1.0,1.0,0.9933774834437086,1.0,1.0,0.9558512173996728,1.0,0.9997927890592623,0.9942408376963351
  grpmax_freq grpmax_ancestry
1 1.000000    eas
2       NA    NA
3 0.063017    afr
4 0.079372    afr
5 0.055919    afr
6 1.000000    eas

Seperate AFs for the different populations

In [ ]:
column_names = c("global_adj","global_raw","nfe_adj","fin_adj","mid_adj","remaining_adj",
                "ami_adj","asj_adj","afr_adj","eas_adj","sas_adj","amr_adj")

final <- separate(data = proc, col = X__uid_5, into = column_names, sep = ",")

[1] 12

## Save results

In [ ]:
write.csv(final,"gnomad_vat_table_processed_MULTI_allele.csv",row.names=F)